/* Execução opcional: CAMPUS_PLAYWRIGHT=/caminho/do/playwright node prototipo/verificacao/fluxos.cjs */
const { chromium } = require(process.env.CAMPUS_PLAYWRIGHT || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const output = path.resolve(__dirname);
const passed = [];
const key = 'campus-em-dia-prototipo-v1';

(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CAMPUS_CHROME || '/opt/google/chrome/chrome', headless: true, args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const mockTiles = target => target.route(/https:\/\/(?:tile\.openstreetmap\.org\/|services\.arcgisonline\.com\/ArcGIS\/rest\/services\/World_Imagery\/MapServer\/tile\/)/, route => route.fulfill({ contentType: 'image/png', body: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') }));
    // A validação automatizada não solicita tiles aos provedores. A inspeção visual é separada.
    await mockTiles(page);
    const errors = [];
    page.on('pageerror', e => { errors.push(e.message); console.error(e.stack); });
    const state = () => page.evaluate(k => JSON.parse(localStorage.getItem(k)), key);
    const app = page.locator('#app');
    const dialog = page.locator('#sheet');
    const check = name => { passed.push(name); console.log('OK: ' + name); };
    const shot = async name => { await page.locator('#toast').evaluate(el => { el.classList.remove('visible'); el.style.visibility = 'hidden'; }); await page.screenshot({ path: path.join(output, 'fluxo-' + name), fullPage: true }); await page.locator('#toast').evaluate(el => el.style.visibility = ''); };
    const route = async target => { await page.evaluate(target => location.hash = '/' + target, target); await page.waitForFunction(target => location.hash === '#/' + target, target); await page.waitForTimeout(70); };
    const demo = async id => { await page.locator(`#demo-profiles [data-id="${id}"]`).click(); await page.waitForTimeout(70); };
    await page.goto('http://127.0.0.1:5173');
    assert.equal(await app.locator('h1').textContent(), 'Nosso campus');
    assert.equal(await app.locator('.map-marker').count(), 7);
    await shot('desktop.png');
    check('Mapa inicial com sete ocorrências ativas e conta de demonstração');
    assert.equal(await page.evaluate(() => CampusMaps.state().zoom), 16);
    await app.locator('[data-action="zoom-in"]').click();
    await page.waitForFunction(() => CampusMaps.state().zoom === 17);
    await app.locator('[data-action="center-map"]').click();
    await app.locator('[data-action="map-style"][data-value="streets"]').click();
    assert.equal(await app.locator('#campus-map').getAttribute('data-layer'), 'streets');
    assert.match(await app.locator('.leaflet-control-attribution').textContent(), /OpenStreetMap/);
    await app.locator('[data-action="map-style"][data-value="satellite"]').click();
    assert.match(await app.locator('.leaflet-control-attribution').textContent(), /Esri/);
    await app.locator('#campus-map').focus();
    const beforePan = await page.evaluate(() => CampusMaps.state().center);
    await page.keyboard.press('ArrowRight');
    await page.waitForFunction(before => CampusMaps.state().center[1] !== before[1], beforePan);
    await app.locator('[data-action="center-map"]').click();
    const marker = app.locator('.map-marker[data-id="027"]');
    await marker.evaluate(el => el.click());
    assert.match(await app.locator('#map-preview').textContent(), /Bebedouro/);
    await app.locator('.map-marker[data-id="026"]').evaluate(el => el.click());
    check('Mapa geográfico: zoom, deslocamento, alternância Satélite/Mapa, atribuição e seleção de marcador');

    await app.locator('[data-action="filters"]').click();
    await dialog.locator('[name="category"]').selectOption('iluminacao');
    await dialog.locator('[name="sector"]').selectOption('eletrica');
    await dialog.locator('[type="submit"]').click();
    assert.equal(await app.locator('.map-marker').count(), 2);
    await app.locator('#map-search').fill('Poste');
    assert.equal(await app.locator('.map-marker').count(), 1);
    await app.locator('[data-action="filters"]').click();
    await dialog.locator('[data-action="clear-filters"]').click();
    check('Busca e filtros combinados de categoria, situação e setor');

    await app.locator('.map-preview[data-action="detail"]').click();
    await app.locator('[data-action="confirm"]').click();
    assert.equal(await app.locator('[data-action="confirm"]').isDisabled(), true);
    assert.equal((await state()).occurrences.find(o => o.id === '026').confirmations.length, 1);
    await app.locator('[data-action="contribute"]').click();
    await dialog.locator('[name="text"]').fill('O segundo poste também apresenta a mesma falha.');
    await dialog.locator('[type="submit"]').click();
    assert.equal((await state()).occurrences.find(o => o.id === '026').contributions.length, 2);
    await page.reload();
    assert.equal(await app.locator('[data-action="confirm"]').isDisabled(), true);
    await app.locator('[data-value="history"]').click();
    assert.equal(await app.locator('.timeline-item').count(), 3);
    await shot('historico.png');
    check('Confirmação única, contribuição textual, histórico e persistência após recarga');

    await route('mapa');
    await app.locator('[data-action="new"]').click();
    await app.locator('[data-action="new-next"]').click();
    assert.match(await app.locator('#location-error').textContent(), /Selecione/);
    await app.locator('#location-picker').click({ position: { x: 150, y: 130 } });
    assert.match(await app.locator('#selected-coordinates').textContent(), /-20\./);
    await app.locator('#location-picker').focus();
    await page.keyboard.press('Enter');
    assert.match(await app.locator('#location-selection').textContent(), /Próximo a/);
    await app.locator('[data-action="location-preset"][data-name="Biblioteca Central"]').click();
    assert.match(await app.locator('#location-selection').textContent(), /Biblioteca/);
    await app.locator('[data-action="new-next"]').click();
    await app.locator('.category-option:has([value="iluminacao"])').click();
    await app.locator('[name="description"]').fill('Lâmpada quebrada na entrada lateral da biblioteca. O local fica escuro ao anoitecer.');
    await app.locator('[name="reference"]').fill('Entrada lateral');
    await app.locator('#photo-input').setInputFiles({ name: 'foto.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') });
    await page.waitForSelector('#upload-label img');
    await app.locator('[type="submit"]').click();
    assert.match(await app.locator('.routing-note').textContent(), /Manutenção elétrica/);
    await shot('registro.png');
    await app.locator('[data-action="publish-occurrence"]').click();
    const created = (await state()).occurrences.find(o => o.id === '028');
    assert.equal(created.status, 'registrada'); assert.equal(created.sector, 'eletrica'); assert.ok(created.photo.startsWith('data:image/png'));
    assert.equal(created.history.length, 1); assert.equal(created.author, 'marina');
    assert.equal(created.lat, -20.761367); assert.equal(created.lng, -42.8677889);
    assert.equal(created.coordinateSource, 'map-click');
    check('Registro em três etapas, validação do local, teclado, foto e encaminhamento pela categoria');

    await demo('joao');
    const queueIds = await app.locator('.occurrence-row').evaluateAll(rows => rows.map(row => row.dataset.id));
    assert.ok(queueIds.includes('028')); assert.ok(!queueIds.includes('027'));
    await shot('manutencao.png');
    await app.locator('[data-action="detail"][data-id="028"]').click();
    await app.locator('[data-status="analise"]').click();
    await dialog.locator('[type="submit"]').click();
    await app.locator('[data-status="andamento"]').click();
    await dialog.locator('[name="note"]').fill('A equipe chegou ao local e iniciou a substituição.');
    await dialog.locator('[type="submit"]').click();
    await app.locator('[data-status="resolvida"]').click();
    await dialog.locator('[type="submit"]').click();
    assert.equal((await state()).occurrences.find(o => o.id === '028').status, 'andamento');
    await dialog.locator('[name="note"]').fill('Substituímos a lâmpada e verificamos o funcionamento da iluminação.');
    await dialog.locator('[type="submit"]').click();
    const resolved = (await state()).occurrences.find(o => o.id === '028');
    assert.equal(resolved.status, 'resolvida'); assert.equal(resolved.history.length, 4); assert.ok(resolved.resolvedAt);
    assert.equal(await app.locator('.manage-box').count(), 0);
    check('Fila restrita aos setores vinculados e ciclo registrada → análise → andamento → resolvida');

    await route('ocorrencia/027');
    assert.equal(await app.locator('.manage-box').count(), 0);
    await route('ocorrencia/024');
    await app.locator('[data-action="transfer"]').click();
    await dialog.locator('[name="sector"]').selectOption('infraestrutura');
    await dialog.locator('[name="note"]').fill('O reparo depende da estrutura de fixação do jardim.');
    await dialog.locator('[type="submit"]').click();
    assert.equal((await state()).occurrences.find(o => o.id === '024').sector, 'infraestrutura');
    assert.equal(await app.locator('.manage-box').count(), 0);
    await route('ocorrencia/023');
    await app.locator('[data-status="encerrada"]').click();
    await dialog.locator('[type="submit"]').click();
    assert.equal((await state()).occurrences.find(o => o.id === '023').status, 'analise');
    await dialog.locator('[name="note"]').fill('O registro foi duplicado e será acompanhado na ocorrência original.');
    await dialog.locator('[type="submit"]').click();
    assert.equal((await state()).occurrences.find(o => o.id === '023').status, 'encerrada');
    check('Bloqueio de atendimento sem vínculo, transferência com histórico e encerramento justificado');

    await demo('ana');
    await shot('administracao.png');
    await route('ocorrencia/026');
    assert.equal(await app.locator('.manage-box').count(), 0);
    await route('configuracao');
    await app.locator('.config-add [data-action="edit-sector"]').click();
    await dialog.locator('[name="name"]').fill('Conservação dos jardins');
    await dialog.locator('[name="description"]').fill('Cuidados com os espaços verdes.');
    await dialog.locator('[type="submit"]').click();
    const newSector = (await state()).sectors.find(s => s.name === 'Conservação dos jardins'); assert.ok(newSector);
    await app.locator('[data-action="edit-sector"][data-id="eletrica"]').click();
    await dialog.locator('[name="active"]').uncheck();
    await dialog.locator('[type="submit"]').click();
    assert.equal((await state()).sectors.find(s => s.id === 'eletrica').active, true);
    await dialog.locator('[data-action="close-sheet"]').click();
    await app.locator('[data-value="categories"]').click();
    await app.locator('.config-add [data-action="edit-category"]').click();
    await dialog.locator('[name="name"]').fill('Jardins');
    await dialog.locator('[name="sector"]').selectOption(newSector.id);
    await dialog.locator('[type="submit"]').click();
    assert.ok((await state()).categories.some(c => c.name === 'Jardins'));
    await app.locator('[data-action="edit-category"][data-id="iluminacao"]').click();
    await dialog.locator('[name="sector"]').selectOption('equipamentos');
    await dialog.locator('[type="submit"]').click();
    assert.equal((await state()).occurrences.find(o => o.id === '026').sector, 'eletrica');
    await app.locator('[data-value="users"]').click();
    await app.locator('[data-action="edit-links"][data-id="joao"]').click();
    await dialog.locator('[name="sectors"][value="hidraulica"]').check();
    await dialog.locator('[type="submit"]').click();
    assert.ok((await state()).users.find(u => u.id === 'joao').sectors.includes('hidraulica'));
    check('Administração sem atendimento automático; setores, categorias e vínculos; preservação de referências');

    await demo('marina'); await page.evaluate(() => location.hash = '/configuracao');
    await page.waitForFunction(() => location.hash === '#/mapa');
    await route('estatisticas');
    await app.locator('#stats-period').selectOption('custom');
    await app.locator('#stats-start').fill('2026-10-02');
    await app.locator('#stats-end').fill('2026-10-02');
    assert.equal(await app.locator('.stat-side b').textContent(), '4 dias');
    await app.locator('#stats-period').selectOption('month');
    await shot('estatisticas.png');
    check('Acesso administrativo bloqueado para membro e média pela data da resolução, inclusive registros anteriores');

    await route('conta');
    await app.locator('[data-action="edit-account"]').click();
    await dialog.locator('[name="name"]').fill('Marina Oliveira Silva');
    await dialog.locator('[type="submit"]').click();
    assert.equal((await state()).users.find(u => u.id === 'marina').name, 'Marina Oliveira Silva');
    await app.locator('[data-action="logout"]').click();
    await page.evaluate(() => location.hash = '/mapa'); await page.waitForFunction(() => location.hash === '#/entrada');
    await shot('entrada.png');
    await app.locator('[data-target="cadastro"]').click();
    await app.locator('[name="name"]').fill('Pessoa de Teste');
    await app.locator('[name="email"]').fill('pessoa@exemplo.com');
    await app.locator('[name="password"]').fill('minhasenha123');
    await app.locator('[type="submit"]').click();
    await page.waitForFunction(() => location.hash === '#/mapa');
    const registered = (await state()).users.find(u => u.email === 'pessoa@exemplo.com');
    assert.equal(registered.role, 'member'); assert.equal(registered.sectors.length, 0); assert.ok(registered.passwordHash);
    assert.ok(!JSON.stringify(await state()).includes('minhasenha123'));
    await route('conta'); await app.locator('[data-action="logout"]').click();
    await app.locator('[name="email"]').fill('pessoa@exemplo.com');
    await app.locator('[name="password"]').fill('minhasenha123');
    await app.locator('[type="submit"]').click();
    await page.waitForFunction(() => location.hash === '#/mapa');
    check('Edição da conta, saída, autenticação obrigatória, cadastro e entrada com senha derivada sem texto puro');

    await demo('marina');
    await route('ocorrencia/027');
    await page.evaluate(() => { window.campusOriginalSetItem = Storage.prototype.setItem; Storage.prototype.setItem = function() { throw new DOMException('Simulação de armazenamento indisponível', 'QuotaExceededError'); }; });
    await app.locator('[data-action="confirm"]').click();
    assert.equal((await state()).occurrences.find(o => o.id === '027').confirmations.length, 0);
    assert.equal(await app.locator('[data-action="confirm"]').isDisabled(), false);
    assert.match(await page.locator('#toast').textContent(), /Não foi possível salvar/);
    await page.evaluate(() => { Storage.prototype.setItem = window.campusOriginalSetItem; delete window.campusOriginalSetItem; });
    check('Falha de gravação informa erro e não altera dados nem apresenta sucesso');
    await route('mapa');
    await page.setViewportSize({ width: 390, height: 844 });
    await shot('celular.png');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.locator('#mobile-profile').selectOption('joao');
    assert.equal(await app.locator('h1').textContent(), 'Demandas do setor');
    await shot('celular-manutencao.png');
    await page.setViewportSize({ width: 360, height: 740 }); await page.locator('#mobile-profile').selectOption('ana');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await app.locator('[data-value="sectors"]').click();
    await app.locator('.config-add [data-action="edit-sector"]').click();
    assert.equal(await page.evaluate(() => { const r = document.querySelector('#sheet').getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth; }), true);
    await page.keyboard.press('Escape'); assert.equal(await dialog.evaluate(el => el.open), false);
    check('Layouts de 390 e 360 px, seleção de perfil móvel e diálogo com Escape');

    const filePage = await browser.newPage({ viewport: { width: 1280, height: 900 } });
    await mockTiles(filePage);
    const fileErrors = []; filePage.on('pageerror', e => fileErrors.push(e.message));
    await filePage.goto('file://' + path.resolve(__dirname, '../index.html'));
    assert.equal(await filePage.locator('#app h1').textContent(), 'Nosso campus');
    assert.equal(fileErrors.length, 0); await filePage.close();
    check('Abertura direta do index.html sem servidor');

    const legacy = JSON.parse(JSON.stringify(await state()));
    delete legacy.geoVersion;
    for (const occurrence of legacy.occurrences) { delete occurrence.lat; delete occurrence.lng; delete occurrence.coordinateSource; occurrence.x = 29; occurrence.y = 37; }
    const migrationPage = await browser.newPage();
    await mockTiles(migrationPage);
    await migrationPage.addInitScript(({ key, data }) => localStorage.setItem(key, JSON.stringify(data)), { key, data: legacy });
    await migrationPage.goto('http://127.0.0.1:5173');
    const migrated = await migrationPage.evaluate(k => JSON.parse(localStorage.getItem(k)), key);
    assert.equal(migrated.geoVersion, 1);
    assert.equal(migrated.occurrences.length, legacy.occurrences.length);
    assert.equal(migrated.users.length, legacy.users.length);
    assert.equal(migrated.occurrences.find(o => o.id === '028').status, 'resolvida');
    assert.equal(migrated.occurrences.find(o => o.id === '026').confirmations.length, 1);
    assert.ok(migrated.occurrences.every(o => Number.isFinite(o.lat) && Number.isFinite(o.lng)));
    assert.equal(migrated.occurrences.find(o => o.id === '028').coordinateSource, 'migrated-approximate');
    await migrationPage.close();
    check('Migração do mapa antigo preserva registros, contas, confirmações e atendimento');
    assert.deepEqual(errors, []);
    fs.writeFileSync(path.join(output, 'resultado.json'), JSON.stringify({ success: true, checks: passed, pageErrors: errors, viewports: ['1440×1000','390×844','360×740'] }, null, 2));
    console.log(`\n${passed.length} grupos de verificação passaram, sem erros JavaScript.`);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
